### ISSUE TITLE
question about weird error on dates validation

### ISSUE THREAD

**Issue by cstmgl** [colindean/keepachangelog-parser-java#11]
Hi all,
I've been using your plugin for a fair bit of time without any problem.
Now I'm experiencing the most weird error that I can't really reproduce.

On a specific project I'm getting consistently an error when I ran my pipelines in jenkins about the parser of the changelog.
The error varies but is something like this:
```
Caused by: java.lang.NumberFormatException: For input string: ".E0"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at cx.cad.keepachangelog.ChangelogEntry$Builder.date(ChangelogEntry.java:161)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.extractHeading2(ChangelogExtractor.java:108)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.getEntries(ChangelogExtractor.java:87)
	at cx.cad.keepachangelog.ChangelogParser.parse(ChangelogParser.java:46)
	at cx.cad.keepachangelog.ChangelogParser$parse$2.call(Unknown Source)
```
I've also had it other ways like:

```
Caused by: java.lang.NumberFormatException: For input string: ""
	at cx.cad.keepachangelog.ChangelogEntry$Builder.date(ChangelogEntry.java:161)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.extractHeading2(ChangelogExtractor.java:108)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.getEntries(ChangelogExtractor.java:87)
	at cx.cad.keepachangelog.ChangelogParser.parse(ChangelogParser.java:46)
	at cx.cad.keepachangelog.ChangelogParser$parse.call(Unknown Source)
```

or 
```
Caused by: java.lang.NumberFormatException: multiple points
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at cx.cad.keepachangelog.ChangelogEntry$Builder.date(ChangelogEntry.java:161)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.extractHeading2(ChangelogExtractor.java:108)
	at cx.cad.keepachangelog.internal.ChangelogExtractor.getEntries(ChangelogExtractor.java:87)
	at cx.cad.keepachangelog.ChangelogParser.parse(ChangelogParser.java:46)
	at cx.cad.keepachangelog.ChangelogParser$parse.call(Unknown Source)
````

```
'For input string: ".113E.2113E2"'
```
etc... it keeps changing as I insert more entries into the changelog

Now I will avoid pasting all the changelog but it's rather standard I would think and the format seems good to me.
I also went over all the dates and can't figure out what the issue might be.
Worst since it only happens in Jenkins it's really hard to debug and I extracted the full text we send to the parser and did a quick unit test to call the parser and also no problem.

I was wondering if you can think of something that might cause this, because my googling skills are not helping me.
Just an additional info, the Jenkins agents were the pipelines are running are in linux.

The format of the changelog is something like this:

```
## Unreleased
### Changed
- Update Library x.y.z to version 1.0.9

## 3.22.0 - 2023-01-24
### Changed
- Update Library x.y.z to version: 1.0.0
### Fixed
- Fix issue with topic addendum suffix 

... etc
```

**Comment by colindean** [comment]
Thanks for using the software. I'm glad someone out there is! I'll help if I can.

Can you provide an excerpt of a failing changelog, something that reliably fails? Are you generating the changelog from something, or is it manually curated?

The parser isn't resilient to deviations from the standard. An absent date should yield a malformed changelog. The version must be first and be a valid SemVer-compliant string, the date must be last and be in ISO-8601 format, and the two _must_ be separated by ` - ` (space, dash, space). I've got some null guards in the builder methods for version and date but I don't recall a condition in which a split on a string will return a null (but it's been 5+ years since I worked on this codebase, or in Java for that matter, haha).

**Comment by cstmgl** [comment]
Thanks for the feedback, to be honest the main problem is really that I can't even find a way to make this fail by sending the changelog to the parser directly from a simple unit test.
It really just happens in my linux machines and it's driving me crazy. But by just looking at the changelog it looks completely normal.
It simply started happening a couple of days ago and with not reason, if I compare the latest tags that worked and the ones that don't the changelog is totally normal (but yes it's manually curated).

Anyway the only thing I can't think of is to try and improve the output so it produces at least the line of full content of what is failing to parse.

**Comment by cstmgl** [comment]
I guess once I'll have improved debug I should be able to sort it out.
thank you
